name = "dns-api-cf"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_id = "2e8371c082e32e5715e2e462cb8b7f5c" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
